name: ketmangi
description: "KeTMangi - Meal Planner App. Plan meals, generate shopping lists, reduce food waste."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.2.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  go_router: ^13.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.4.0
  uuid: ^4.2.1
  intl: ^0.19.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
